### ISSUE TITLE
Source code from STM32CubeF4 package does not exist

### ISSUE THREAD

**Issue by hooddanielc** [STMicroelectronics/STM32CubeF4#1]
**Setup**
 * Latest version of git
 * Any compiler

**Describe the bug**
Unable to compile code

**How To Reproduce**
1. Clone the repository: `git clone https://github.com/STMicroelectronics/STM32CubeF4.git`
2. Locate any `.c` file

**Unexpected Behavior**
Unable to find any source code containing  the `STM32CubeF4` package.

**Expected Behavior**
Repository should contain latest version of code from `STM32CubeF4`. The source code should match download from [STMicroelectronics website tools and software part number STM32CubeF4](https://www.st.com/content/st_com/en/products/embedded-software/mcu-mpu-embedded-software/stm32-embedded-software/stm32cube-mcu-mpu-packages/stm32cubef4.html)

**Screenshots**
![DeepinScreenshot_select-area_20190511150907](https://user-images.githubusercontent.com/1351734/57575439-f755e600-73fe-11e9-9527-dd353cd6d66b.png)

**Comment by ALABSTM** [comment]
Dear Daniel Hood,

Thank you for your interest. We are presently working on this. We aim to have all STM32Cube packages available on Github soon.

We cannot share a date for the moment. We will keep you informed.

With regards

**Comment by ALABSTM** [comment]
Dear Daniel,

STM32CubeF4 package (v1.24.1) has just been published on GitHub. We hope this addresses your request. In such case this issue could be closed. Thank you for your patience.

With regards,

**Comment by hooddanielc** [comment]
lgtm
