### ISSUE TITLE
FatFS driver diskio is_initialized is always set to true

### ISSUE THREAD

**Issue by DeeFuse** [STMicroelectronics/STM32CubeF4#110]
When using the CubeMX FatFS implementation the function [disk_initialize](https://github.com/STMicroelectronics/STM32CubeF4/blob/4aba24d78fef03d797a82b258f37dbc84728bbb5/Middlewares/Third_Party/FatFS/src/diskio.c#L51) will always set the "[is_initialized](https://github.com/STMicroelectronics/STM32CubeF4/blob/4aba24d78fef03d797a82b258f37dbc84728bbb5/Middlewares/Third_Party/FatFS/src/diskio.c#L59)" flag to 1 without checking the drivers return value.

That causes the next call to a fatfs function to run into a timeout in the diskread functions, instead of trying to remount the volume.

[ST Community Bugreport](https://community.st.com/s/question/0D50X00009fEXdDSAW/bug-report-if-fmount-fails-once-it-will-not-work-again)

**Comment by RKOUSTM** [comment]
Hi @DeeFuse, 

Thank you for your report. This request will be forwarded to our development teams for deeper analysis. We will be back to you as soon as they provide me with their answer.

This duplicated issue will remain closed. The pull-request https://github.com/STMicroelectronics/STM32CubeF4/pull/111 that you reported will be kept open to track the point.

Thank you for you again for your report.

With regards,
