### ISSUE TITLE
lwIP project could not work in stm32cubeide

### ISSUE THREAD

**Issue by taehyun9203** [STMicroelectronics/STM32CubeF4#166]
Hello, I had a problem with the lwIP project not working on STM32CubeIDE using the Nucleo-F429ZI board.

The cause of the problem is that the default LWIP_RAM_HEAP_POINTER default value is 0x30044000, and if STM32IDE generates code with that value, it is accessing a non-existent memory area, resulting in a hard fault.

So the solution can be summarized in two ways.
The first is to comment LWIP_RAM_HEAP_POINTER in lwipopts.h among the codes responsible for the lwip function (Figure 1).
The second is to disable ICMP checksum-related features in the Ethernet Configuration window (Figure 2).

Figure 1
![image](https://github.com/STMicroelectronics/STM32CubeF4/assets/41182842/211806b8-4f64-4a66-a291-a04832d641a4)

Figure 2
![image](https://github.com/STMicroelectronics/STM32CubeF4/assets/41182842/60577bdc-508b-4585-9a3b-3ddf1dae2389)

**Comment by ASEHSTM** [comment]
Hello @taehyun9203,

Thank you for your report. You are Right. However, this issue has been rectified in version 6.6.0 of STM32cubeMX.

With Regards,

**Comment by ASEHSTM** [comment]
Hello @taehyun9203,

Please allow me to close this thread. You may reopen it at any time if you have any details to share with us. 
Thank you 

With regards,
