### ISSUE TITLE
How to use FPU to actively trigger IDC interrupt

### ISSUE THREAD

**Issue by loatwith** [STMicroelectronics/STM32CubeF4#175]
Hi
I want to test the fpu interrupt in syscfg_cfgr1 of stm32g431

SYSCFG configuration register 1 (SYSCFG_CFGR1)

FPU_IE[5]: Inexact interrupt enable
FPU_IE[4]: Input denormal interrupt enable
FPU_IE[3]: Overflow interrupt enable
FPU_IE[2]: underflow interrupt enable
FPU_IE[1]: Divide-by-zero interrupt enable
FPU_IE[0]: Invalid operation interrupt enable

I am very confused about how to trigger the Input denormal interrupt（FPU_IE[4]）

I am waiting for your answer

**Comment by ALABSTM** [comment]
Hi @loatwith,

Thank you for your question. However, as indicated in the [CONTRIBUTING.md](https://github.com/STMicroelectronics/STM32CubeF4/blob/master/CONTRIBUTING.md#3-support-requests-and-questions) file, this support channel is mainly dedicated to issues directly impacting the software provided within this repository.

For any other support request, please submit your question to the [ST Community](https://community.st.com/s/topiccatalog). There you should find the answers and the support you are looking for.

Please allow me to close this thread. Thank you for your comprehension.

With regards,
