### ISSUE TITLE
Please publish v1.28.1 tag

### ISSUE THREAD

**Issue by bmcdonnell-fb** [STMicroelectronics/STM32CubeF4#177]
**Describe the set-up**
 * N/A

**Additional context**
- STM32CubeF4 v1.28.1 is available as a download from [the product page](https://www.st.com/en/embedded-software/stm32cubef4.html), but the `v1.28.1` tag is not in this repo. Please push it.

**Screenshots**

![image](https://github.com/STMicroelectronics/STM32CubeF4/assets/81983488/888814e4-33ea-41e9-8c3a-422a36a8190e)

![image](https://github.com/STMicroelectronics/STM32CubeF4/assets/81983488/b3883a5d-d2ed-44c3-9fe3-dda8b184827a)

**Comment by RJMSTM** [comment]
Hello @bmcdonnell-fb,

We apologize for any inconvenience caused by the delay, The STM32CubeF4 v1.28.1 is now released on GitHub.
83778d5c95cb01695c7facbf095db3ab445532ea

Regards,
