### ISSUE TITLE
Cannot exclude BSP submodules when pulling STM32CubeF4 into superproject

### ISSUE THREAD

**Issue by davidstephensonfocusrite** [STMicroelectronics/STM32CubeF4#178]
I am working on a commercial project where we wish to benefit from STM32CubeF4 by pulling it into our repository as a submodule.
STM32CubeF4 has two submodules of it's own that contain headers and source critical for building an executable:
- Drivers/CMSIS/Device/ST/STM32F4xx
- Drivers/STM32F4xx_HAL_Driver
To pull these submodules in as well we have to perform
`git submodule update --init --recursive`
However, doing so pulls in a whole wealth of BSP submodules which are of absolutely no value to us and take up space. Can you provide a means to exclude those from a submodule update?
Thanks

**Comment by ALABSTM** [comment]
Hi @davidstephensonfocusrite,

Thank you for your question. To pull updates only of HAL and CMSIS submodules while ignoring the others, you can customize your command like below:

```bash
git submodule update --init -- "Drivers/CMSIS/Device/ST/STM32F4xx" "Drivers/STM32F4xx_HAL_Driver"
``` 

With regards,
