### ISSUE TITLE
tag for v1.25.1 missing?

### ISSUE THREAD

**Issue by fschwa** [STMicroelectronics/STM32CubeF4#40]
My installation of CubeIDE updated the firmware package to v1.25.1 today, which apparently is already a few weeks old. But there is no tag, so checking for changes since 1.25.0 is not possible here.

Is there a reason for this?

**Comment by ASELSTM** [comment]
Hi @fschwa,

Thank you for your interest and for your contribution. The STM32CubeF4 package (v1.25.1) is not yet available on GitHub, it will be published in the coming days.
Stay tuned.

With regards,

**Comment by ASELSTM** [comment]
Hi @fschwa,

STM32CubeF4 package (v1.25.1) has just been published on GitHub. We hope this addresses your request. Please allow me then to close this issue.

With regards,
