### ISSUE TITLE
Include file versioning for every file

### ISSUE THREAD

**Issue by robcazzaro** [STMicroelectronics/STM32CubeF4#44]
I frequently find example code and STM32 projects on the web using HAL files or middleware like USB. None of the files include version information, and it's almost impossible to find out what specific version a developer used. As a result, it's very hard to get things working since the changes from version to version are sometimes very significant.

I suggest creating a script or batch file in your production environment, so that every time you are ready for a release, you can include version information in the header of each file (where you now have the @file name.

Lack of versioning makes it impossible to reuse old code, and it's such a simple thing to implement

**Comment by RKOUSTM** [comment]
Hi @robcazzaro,

First, allow me to thank you for your contribution. However, no plain for our technical team to treat this point where we want to avoid that each file is modified, artificially, with each version. Thank you once again for your contribution.

Please, allow me to close this issue. Thank you for your comprehension.

With regards,
