### ISSUE TITLE
STM32 F411E I2C hang 

### ISSUE THREAD

**Issue by WojciechBernat** [STMicroelectronics/STM32CubeF4#45]
STM32F411E-DISCO
STM32CubeIDE Version: 1.2.1 Build: 5190_20200115_1224 (UTC)

When I was using HAL_I2C_Mem_Read when I detected problem with I2C_RequestMemoryRead. 
I2C_RequestMemoryRead always returned HAL_ERROR. 
When I was creating new project I changed frimware version for F411 from 1.24.2 to 1.24.0.
This action fixed this issue. 

**How To Reproduce**
1. Indicate the global behavior of your application project.
I have no I2C communiction. 

2. The modules that you suspect to be the cause of the problem (Driver, BSP, MW ...).
stm32f4xx_hali2c.h
stm32f4xx_hali2c.c

3. The use case that generates the problem.
Communication by i2c with LSM303DLHC on discovery board.
Use HAL_I2C_Mem_Read -  this function always returns HAL_ERROR

4. How we can reproduce the problem.
Generate project in CubeIDE for LSM303 communication. Use HAL_I2C_Mem_Read form 1.24.2 firmware version.

**Comment by ASELSTM** [comment]
Hi @WojciechBernat, 

Thank you for your contribution.

Could you try with the latest firmware release **(V1.25.1)** and check if you still have the same problem ? 

With regards,

**Comment by WojciechBernat** [comment]
Hi

Thank you for new software.
I downloaded software and replaced HAL's spi driver.
I ran tests and it has worked fine.

With regards,
Wojciech Bernat

wt., 6 paź 2020 o 13:31 ASELSTM <notifications@github.com> napisał(a):

**Comment by WojciechBernat** [comment]
Hi

I made a mistake. I'm working on few projects in the same time and mistake
project.
I check how new I2C driver is working with my project. It's working
correct.
I'm very sorry for mistake.

With regards,
Wojciech Bernat


niedz., 11 paź 2020 o 10:50 Wojciech Bernat <wojciechbernat95@gmail.com>
napisał(a):

**Comment by ASELSTM** [comment]
Hi @WojciechBernat, 

Glad to know that everything is working well.  Please allow me then to close this thread. Thank you again for your contribution.

With regards,
