### ISSUE TITLE
usbd_cdc_if.c (generated) and usbd_cdc_if_template.c out of sync

### ISSUE THREAD

**Issue by jrahlf** [STMicroelectronics/STM32CubeF4#50]
If you generate a project with USB CDC via CubeMX, the following variable and respective logic is missing from usbd_cdc_if.c:

https://github.com/STMicroelectronics/STM32CubeF4/blob/2d5b78e2da98fb44e028d87f4ff815427991affc/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc_if_template.c#L82

I tested this with version 1.25.2. I think this might affect other repos as well.

**Comment by ALABSTM** [comment]
Hi @jrahlf,

Thank you for your report. However, as this is related to **Cube MX**, it is out of our scope. Please submit your finding to the **community** in the dedicated section [here](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx).

Please allow me to close this issue. Thank you for your comprehension.

With regards,
