### ISSUE TITLE
Definition of I2C_MEMADD_SIZE_16BIT has an incorrect value

### ISSUE THREAD

**Issue by armandas** [STMicroelectronics/STM32CubeF4#53]
Currently, the `stm32f4xx_hal_i2c.h` has the following definition of I2C_Memory_Address_Size:

```cpp
/** @defgroup I2C_Memory_Address_Size I2C Memory Address Size
  * @{
  */
#define I2C_MEMADD_SIZE_8BIT            0x00000001U
#define I2C_MEMADD_SIZE_16BIT           0x00000010U
/**
  * @}
  */
```

The value for 8-bit memory address is 1 (byte) as expected, but the value for 16-bit address is 16. In other repositories this definition has a value of 2.

**Comment by RKOUSTM** [comment]
Hi @armandas,

Thank you for contribution. According to our development team, the value of the memory address is defined randomly and it will be correctly generated in the HAL .  

Please allow me then to close this thread. Thank you for your comprehension and thank you again for your contribution.

With regards
