### ISSUE TITLE
PTP(IEEE-1588 Precision Time Protocol) Example

### ISSUE THREAD

**Issue by sysizlayan** [STMicroelectronics/STM32CubeF4#56]
Hello all,
Hardware PTP support seems available in ethernet enabled STM32 MCUs. Yet, there is no application note or example code available.
The only example I can find is:
https://github.com/mpthompson/stm32_f4_ptpd
Yet the boards used in this project seem obsolete and it has been 7 years since the last update.

Do you guys have a plan to include a PTP example? 
Thanks.

**Comment by RKOUSTM** [comment]
Hi @sysizlayan,

Thank you for your contribution. According to our technical team, no plan to add a IEEE-1588 Precision Time Protocol application in the frame of a future release. 

Please allow me to close this thread. We will keep you informed, if we have any update concerning add of PTP application.

Thank you for your comprehension and thank you once more for your contribution

With regards,
