### ISSUE TITLE
STM32F412Cx USB CDC: HAL_GPIO_EXTI_Callback() generated in usbd_conf.c

### ISSUE THREAD

**Issue by fronders** [STMicroelectronics/STM32CubeF4#57]
I am using CubeMX v6.1.1 with CubeF4 v1.25.2 to generate code for STM32F412CGUx with STM32CubeIDE.

The app generates usbd_conf.c with following function included:
``` cpp
/**
  * @brief  Handle USB VBUS detection upon external interrupt
  * @param  GPIO_Pin
  * @retval None
  */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
  if (GPIO_Pin == GPIO_PIN_9)
  {
    HAL_PCDEx_BCD_VBUSDetect(&hpcd_USB_OTG_FS);
  }
}
```
This causes linkage errors when there is a user-implemented EXTI Callback.
The issue happens regardless of VBUS Sensing setting in CubeMX - even when it is off, the callback still gets generated (not saying it should be generated that way when VBUS Sensing is on).

This was reproducible with STM32F412RE but NOT with STM32F446RE or STM32F411CEUx

Please see generated files attached: [stm32f412-usb-vbus-off.zip](https://github.com/STMicroelectronics/STM32CubeF4/files/5851603/stm32f412-usb-vbus-off.zip)

USB settings used:
![image](https://user-images.githubusercontent.com/15352046/105401004-4f159e80-5c2e-11eb-8ae4-d118f3334b28.png)
![image](https://user-images.githubusercontent.com/15352046/105401039-59379d00-5c2e-11eb-958c-971479addbee.png)

**Comment by ALABSTM** [comment]
Hello @fronders,

Please excuse the somewhat late reply and thank you for having reported. It looks this point is rather related to the Cube MX tool. Such points are out of the scope of this repository. Would you please mind submitting your report to the **ST Community** into the dedicated [section](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx)?

Plase allow me to close this issue. Thank you for your comprehension.

With regards,
