### ISSUE TITLE
STM32F401-Discovery Templates_LL, System Clock Configuration Error.

### ISSUE THREAD

**Issue by cnxiaochun** [STMicroelectronics/STM32CubeF4#79]
STM32F401-Discovery/Templates_LL/Src/main.c
STM32F401RE-Nucleo/Templates_LL/Src/main.c

/**
  * @brief  System Clock Configuration
  *         The system Clock is configured as follow :
  *            System Clock source            = PLL (HSE)
  *            SYSCLK(Hz)                     = 84000000
  *            HCLK(Hz)                       = 84000000
  *            AHB Prescaler                  = 1
  *            APB1 Prescaler                 = 1            ----> It should be 2
  *            APB2 Prescaler                 = 2          -----> It should be 1
  * /
  
 `
  LL_RCC_SetAPB1Prescaler(LL_RCC_APB1_DIV_1);  /*  It should be LL_RCC_APB1_DIV_2 */
  LL_RCC_SetAPB2Prescaler(LL_RCC_APB2_DIV_2); /*  It should be LL_RCC_APB2_DIV_1 */
`

STM32F401-Discovery/Templates_LL/Src/main.c

 `
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;  /* It's right */
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;  /* It's right */
`

Thank you

**Comment by RKOUSTM** [comment]
Hi @cnxiaochun,

Thank you for your contribution. The issue you pointed out has been confirmed. An internal tracker has been logged and a fix will be implemented and made available in the frame of a future release.

Thank you once again for your contribution.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 108823

**Comment by RKOUSTM** [comment]
Hi @cnxiaochun,

The fix you requested has been implemented and is now available in the frame of the latest STM32CubeF4 package V1.26.2 release. 

This issue can be closed now. Thank you again for your contribution.

With regards,
