### ISSUE TITLE
Bug in HAL_EXTI_GetConfigLine()

### ISSUE THREAD

**Issue by JasonShiao** [STMicroelectronics/STM32CubeF4#81]
I think 
` pExtiConfig->GPIOSel = ((regval << (SYSCFG_EXTICR1_EXTI1_Pos * (3uL - (linepos & 0x03u)))) >> 24);
`
should be 
`
 pExtiConfig->GPIOSel = ((regval << (SYSCFG_EXTICR1_EXTI1_Pos * (3uL - (linepos & 0x03u)))) >> 12);
`

**Comment by ASELSTM** [comment]
ST Internal Reference: 110689

**Comment by ALABSTM** [comment]
Related to: [STM32CubeF7#16](https://github.com/STMicroelectronics/STM32CubeF7/issues/16)

**Comment by ASELSTM** [comment]
Hi @JasonShiao,

This issue has been fixed in the frame of version v1.27.0 of the STM32CubeF4 published recently. Please allow me then to close this thread.

With regards,
